# Generated by Django 2.1.7 on 2019-03-02 16:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data de Teste')),
                ('ping', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Serviço Respondeu')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('domain', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PesquisaNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(default='', max_length=30)),
                ('action_view', models.CharField(default='', max_length=1000)),
                ('restritivo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Restrige aprofundamento da árvore')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='api.PesquisaNode', verbose_name='Filhos')),
            ],
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='domain',
        ),
        migrations.AddField(
            model_name='municipio',
            name='radical',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='action',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Municipio'),
        ),
        migrations.AddField(
            model_name='action',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.PesquisaNode'),
        ),
    ]
