# Generated by Django 2.1.7 on 2019-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190302_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisanode',
            name='action_view',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
