# Generated by Django 2.1.7 on 2019-03-02 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190302_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisanode',
            name='protocolo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('https', 'https'), ('http', 'http'), ('wss', 'wss'), ('ws', 'ws')], default='https', max_length=10), default=list, size=0),
            preserve_default=False,
        ),
    ]
