# Generated by Django 2.1.7 on 2019-03-02 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pesquisanode_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisanode',
            name='protocolo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('https', 'https'), ('http', 'http'), ('wss', 'wss'), ('ws', 'ws')], default='https', max_length=10), size=None),
        ),
    ]
