# Generated by Django 2.1.7 on 2019-03-02 16:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190302_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisanode',
            name='protocolo',
            field=api.models.ChoiceArrayField(base_field=models.CharField(choices=[('https', 'https'), ('http', 'http'), ('wss', 'wss'), ('ws', 'ws')], max_length=10), default=list, size=None),
        ),
    ]
