# Generated by Django 2.1.7 on 2019-03-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190302_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisanode',
            name='tipo_response',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pesquisanode',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='api.PesquisaNode', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='pesquisanode',
            name='servico',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
