# Generated by Django 2.1.7 on 2019-03-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190302_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='radical',
            new_name='dmoain',
        ),
    ]
