# Generated by Django 2.1.7 on 2019-03-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190302_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='dmoain',
            new_name='domain',
        ),
    ]
