# Generated by Django 2.1.7 on 2019-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190302_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisanode',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
