# Generated by Django 2.1.7 on 2019-03-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pesquisanode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisanode',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pesquisanode',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
